"""Compile SQLAlchemy metadata into MySQL DDL (sql/02_schema.sql) and the seed SQL.

Usage:
    python -m app.tools.export_schema            # writes sql/02_schema.sql
    python -m app.tools.export_seed              # via app.tools.export_schema seed
"""
from __future__ import annotations

import sys
from pathlib import Path

from sqlalchemy.dialects import mysql
from sqlalchemy.schema import CreateTable

from .. import models  # noqa: F401  (register all mappers)
from ..database import Base

HEADER = """-- =============================================================================
--  VIJAY VARGIYA GROUP OF HOSPITALS - MySQL schema (generated by app.tools.export_schema)
--  Apply with:
--    mysql -u root -p vijay_vargiya_hospital < sql/02_schema.sql
-- =============================================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

"""

VIEWS = """
-- ---------------------------------------------------------------------------
--  REPORTING VIEWS  (read-only helpers for analytics / BI / reception TV)
--  Granted to vvh_readonly and vvh_app by this script.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_appointments_today AS
SELECT a.id, a.appointment_code, p.patient_code, p.full_name AS patient_name, p.phone,
       d.full_name AS doctor_name, s.name AS specialty, a.appointment_date, a.start_time,
       a.token_number, a.status, a.queue_status, a.source
FROM appointments a
JOIN patients p  ON p.id = a.patient_id
LEFT JOIN doctors d ON d.id = a.doctor_id
LEFT JOIN specialties s ON s.id = a.specialty_id
WHERE a.appointment_date = CURDATE();

CREATE OR REPLACE VIEW v_outstanding_invoices AS
SELECT i.id, i.invoice_number, p.patient_code, p.full_name AS patient_name, p.phone,
       i.total_amount, i.paid_amount, i.balance_amount, i.status, i.issued_at, i.due_date
FROM invoices i JOIN patients p ON p.id = i.patient_id
WHERE i.balance_amount > 0 AND i.status IN ('UNPAID','PARTIAL');

CREATE OR REPLACE VIEW v_doctor_daily_load AS
SELECT d.id AS doctor_id, d.doctor_code, d.full_name AS doctor_name, s.name AS specialty,
       a.appointment_date,
       COUNT(*) AS appointments,
       SUM(a.status = 'COMPLETED') AS completed,
       SUM(a.status = 'CANCELLED') AS cancelled,
       SUM(a.queue_status = 'NO_SHOW') AS no_shows,
       SUM(CASE WHEN a.status IN ('PENDING','CONFIRMED') THEN 1 ELSE 0 END) AS upcoming
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
LEFT JOIN specialties s ON s.id = d.specialty_id
GROUP BY d.id, d.doctor_code, d.full_name, s.name, a.appointment_date;

CREATE OR REPLACE VIEW v_ai_daily_summary AS
SELECT DATE(c.started_at) AS day, c.status, COUNT(*) AS conversations,
       SUM(c.escalation_count) AS escalations,
       ROUND(AVG(c.message_count), 1) AS avg_messages,
       SUM(c.successful_bookings) AS bookings,
       ROUND(AVG(c.avg_response_ms), 0) AS avg_response_ms
FROM ai_conversations c
GROUP BY DATE(c.started_at), c.status;

GRANT SELECT ON `vijay_vargiya_hospital`.v_appointments_today TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_outstanding_invoices TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_doctor_daily_load TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_ai_daily_summary TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_appointments_today TO 'vvh_app'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_outstanding_invoices TO 'vvh_app'@'localhost';
"""

FOOTER = """
SET FOREIGN_KEY_CHECKS = 1;
-- End of schema
"""


def _index_clause(table, index) -> str | None:
    """Render one SQLAlchemy Index as an inline MySQL KEY clause (mysqldump style).

    Indexes are emitted *inside* CREATE TABLE so the whole script stays idempotent:
    a standalone ``CREATE INDEX`` cannot be made re-runnable on MySQL 8
    (``CREATE INDEX IF NOT EXISTS`` is MariaDB-only) and fails with
    ERROR 1061 Duplicate key name on a second run.
    """
    cols: list[str] = []
    for expr in index.expressions:
        name = getattr(expr, "name", None)
        if name is None:
            return None                     # expression index -> cannot inline, skip
        cols.append(f"`{name}`")
    prefix = "UNIQUE KEY" if index.unique else "KEY"
    return f"{prefix} `{index.name}` ({', '.join(cols)})"


def export(path: str = "sql/02_schema.sql") -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    dialect = mysql.dialect()
    parts = [HEADER]
    skipped: list[str] = []
    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=dialect)).strip()
        # merge the table's Index objects into the CREATE TABLE body
        inline = [clause for clause in (_index_clause(table, ix) for ix in table.indexes) if clause]
        skipped += [ix.name for ix in table.indexes if _index_clause(table, ix) is None]
        if inline:
            head, sep, _ = ddl.rpartition("\n)")
            if sep:
                ddl = f"{head},\n  " + ",\n  ".join(inline) + "\n)"
        ddl = ddl.replace("CREATE TABLE", "CREATE TABLE IF NOT EXISTS", 1)
        parts.append(ddl.rstrip() + " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 "
                                     "COLLATE=utf8mb4_unicode_ci;\n\n")
    parts.append(VIEWS.lstrip("\n"))
    parts.append(FOOTER)
    out.write_text("".join(parts))
    if skipped:
        print(f"  note: {len(skipped)} expression index(es) could not be inlined: {skipped}")
    return out


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "sql/02_schema.sql"
    written = export(target)
    tables = len(Base.metadata.sorted_tables)
    print(f"Wrote {written} ({tables} tables)")
