"""Export the RBAC + master data seed as MySQL INSERT statements (sql/03_seed.sql)."""
from __future__ import annotations

import re
import sys
from pathlib import Path

from ..rbac import PERMISSIONS, ROLE_PERMISSIONS, ROLES
from ..security import hash_password

HEADER = """-- =============================================================================
--  VIJAY VARGIYA GROUP OF HOSPITALS - seed data (generated by app.tools.export_seed)
--  Roles, permissions, demo staff logins, specialties, medicines and holidays.
--  Apply with:
--    mysql -u root -p vijay_vargiya_hospital < sql/03_seed.sql
--  NOTE: patient/doctor demo history is generated by `python -m app.seed` so the
--        slot engine and billing maths stay consistent.
-- =============================================================================
SET NAMES utf8mb4;
USE `vijay_vargiya_hospital`;

"""

STAFF = [
    ("Vijay Vargiya", "superadmin@vijayvargiyahospital.in", "SUPER_ADMIN", "SuperAdmin@123", "9000000001"),
    ("Hospital Admin", "admin@vijayvargiyahospital.in", "ADMIN", "Admin@123", "9000000002"),
    ("Front Desk - Ritu", "reception@vijayvargiyahospital.in", "RECEPTIONIST", "Reception@123", "9000000003"),
    ("Accounts - Mahesh", "accounts@vijayvargiyahospital.in", "ACCOUNTANT", "Accounts@123", "9000000004"),
]

SPECIALTIES = [
    ("GENMED", "General Medicine", "Fever, infections, diabetes, blood pressure and general complaints", 500),
    ("CARDIOLOGY", "Cardiology", "Heart, chest pain, blood pressure and ECG evaluation", 900),
    ("ORTHO", "Orthopaedics", "Bones, joints, fractures, knee and back pain", 700),
    ("DERMA", "Dermatology", "Skin, hair, nails, acne and allergies", 600),
    ("PEDIA", "Paediatrics", "Newborn and child health, vaccination and growth", 600),
    ("GYNAE", "Obstetrics & Gynaecology", "Pregnancy, menstrual health and women's wellness", 800),
    ("ENT", "ENT", "Ear, nose, throat, sinus and hearing complaints", 600),
    ("NEURO", "Neurology", "Headache, migraine, seizures and nerve problems", 1000),
    ("GASTRO", "Gastroenterology", "Stomach, liver, acidity and digestion", 800),
    ("PULMO", "Pulmonology", "Asthma, breathing difficulty and chest infections", 800),
    ("OPHTHAL", "Ophthalmology", "Eye check-up, vision and eye infections", 600),
    ("PSYCH", "Psychiatry", "Stress, anxiety, sleep and mental wellbeing", 900),
]

CONCERNS = {
    "GENMED": ["fever", "cold", "cough", "throat", "flu", "weakness", "body ache", "typhoid", "infection",
               "diabetes", "sugar", "blood pressure", "bp", "fatigue", "vomiting", "loose motion", "diarrhoea"],
    "CARDIOLOGY": ["chest pain", "heart", "palpitations", "breathless", "cholesterol", "ecg", "angina"],
    "ORTHO": ["knee", "joint", "fracture", "back pain", "sprain", "shoulder", "bone", "neck pain", "ghutna",
              "kamar dard", "sciatica"],
    "DERMA": ["rash", "skin", "itching", "acne", "pimple", "hair fall", "eczema", "fungal", "allergy", "khujli"],
    "PEDIA": ["child", "baby", "infant", "vaccination", "teething", "children", "bacche", "newborn"],
    "GYNAE": ["pregnancy", "periods", "menstrual", "pcos", "white discharge", "gynae", "irregular periods"],
    "ENT": ["ear", "nose", "throat", "sinus", "tonsil", "hearing", "snoring", "kaan", "naak"],
    "NEURO": ["headache", "migraine", "seizure", "dizziness", "numbness", "vertigo", "fits", "sir dard"],
    "GASTRO": ["stomach", "acidity", "gas", "ulcer", "liver", "jaundice", "constipation", "abdomen", "pet dard"],
    "PULMO": ["asthma", "breathing", "wheezing", "tuberculosis", "tb", "bronchitis", "saans"],
    "OPHTHAL": ["eye", "vision", "blurred", "cataract", "chashma", "aankh"],
    "PSYCH": ["stress", "anxiety", "depression", "sleep", "insomnia", "panic", "mental", "tension"],
}

MEDICINES = [
    ("Paracetamol", "Acetaminophen", "TABLET", "500 mg", "1-0-1", "After food", "5 days"),
    ("Azithromycin", "Azithromycin", "TABLET", "500 mg", "0-1-0", "After food", "3 days"),
    ("Amoxicillin + Clavulanate", "Co-amoxiclav", "TABLET", "625 mg", "1-0-1", "After food", "5 days"),
    ("Cetirizine", "Cetirizine", "TABLET", "10 mg", "0-0-1", "After food", "5 days"),
    ("Pantoprazole", "Pantoprazole", "TABLET", "40 mg", "1-0-0", "Before food", "14 days"),
    ("Ondansetron", "Ondansetron", "TABLET", "4 mg", "SOS", "When needed", "3 days"),
    ("ORS", "Oral Rehydration Salt", "SACHET", "-", "1-1-1", "With water", "3 days"),
    ("Metformin", "Metformin", "TABLET", "500 mg", "1-0-1", "After food", "30 days"),
    ("Amlodipine", "Amlodipine", "TABLET", "5 mg", "1-0-0", "Morning", "30 days"),
    ("Atorvastatin", "Atorvastatin", "TABLET", "10 mg", "0-0-1", "Night", "30 days"),
]



# ---------------------------------------------------------------------------
# Column-coverage guard
# ---------------------------------------------------------------------------
#  Every NOT NULL column without a server default must appear in the INSERT
#  column list, otherwise MySQL strict mode rejects the row with ERROR 1364
#  ("Field 'x' doesn't have a default value"). This check runs at generation
#  time so the seed can never silently drift from the models again.
# ---------------------------------------------------------------------------
from .. import models  # noqa: F401  (register mappers)
from ..database import Base

_SEEN: dict[str, set[str]] = {}


def _required_columns(table_name: str) -> set[str]:
    table = Base.metadata.tables[table_name]
    required: set[str] = set()
    for col in table.columns:
        if col.primary_key or col.nullable:
            continue
        if col.default is not None or col.server_default is not None:
            continue
        required.add(col.name)
    return required


def _note_columns(table_name: str, columns: str) -> None:
    _SEEN.setdefault(table_name, set()).update(c.strip() for c in columns.split(",") if c.strip())


def audit_columns() -> list[str]:
    """Return human-readable descriptions of any uncovered NOT NULL columns."""
    problems: list[str] = []
    for table_name, provided in _SEEN.items():
        missing = sorted(_required_columns(table_name) - provided)
        if missing:
            problems.append(f"{table_name}: {', '.join(missing)}")
    return problems


def _esc(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")



def audit_statement_order(sql_text: str) -> list[str]:
    """Flag INSERT ... SELECT statements that read a table populated *later*.

    A SELECT over a table that is still empty inserts zero rows without raising
    an error (MySQL happily reports "0 rows affected"), so ordering mistakes are
    invisible at apply time. This catches them at generation time.
    """
    statements = [st.strip() for st in sql_text.split(";") if st.strip()]
    first_insert: dict[str, int] = {}
    inserts: list[tuple[int, str, list[str]]] = []
    ref_re = re.compile(r"\b(?:FROM|JOIN)\s+([a-z_][a-z0-9_]*)", re.IGNORECASE)
    ins_re = re.compile(r"INSERT\s+INTO\s+([a-z_][a-z0-9_]*)", re.IGNORECASE)
    for pos, statement in enumerate(statements):
        clean = "\n".join(line for line in statement.splitlines() if not line.strip().startswith("--"))
        target = ins_re.search(clean)
        if not target:
            continue
        table = target.group(1).lower()
        first_insert.setdefault(table, pos)
        inserts.append((pos, table, [r.lower() for r in ref_re.findall(clean)]))
    problems: list[str] = []
    for pos, table, refs in inserts:
        for ref in refs:
            if ref == table or ref == "dual":
                continue
            ref_pos = first_insert.get(ref)
            if ref_pos is not None and ref_pos > pos:
                problems.append(f"ordering: statement #{pos} inserts into '{table}' using '{ref}', "
                                f"which is only populated at statement #{ref_pos} (0 rows would be inserted)")
    return problems

def export(path: str = "sql/03_seed.sql") -> list[str]:
    """Write sql/03_seed.sql and return a list of audit warnings (empty = clean)."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    sql: list[str] = [HEADER]

    _note_columns("roles", "name, description, is_system, created_at, updated_at")
    _note_columns("permissions", "code, module, description, created_at, updated_at")
    _note_columns("users", "uuid, full_name, email, phone, password_hash, role_id, is_active, is_verified, "
                           "must_change_password, phone_verified, failed_login_attempts, "
                           "password_changed_at, created_at, updated_at")
    _note_columns("doctors", "doctor_code, user_id, specialty_id, full_name, email, qualifications, "
                             "experience_years, registration_no, languages, consultation_fee, follow_up_fee, "
                             "slot_duration_minutes, daily_capacity, room_number, is_available_for_ai_booking, "
                             "is_active, rating_avg, rating_count, created_at, updated_at")
    _note_columns("doctor_schedules", "doctor_id, day_of_week, start_time, end_time, break_start, break_end, "
                                      "slot_duration_minutes, capacity_per_slot, is_active, created_at, updated_at")
    _note_columns("specialties", "code, name, description, consultation_fee, is_active, created_at, updated_at")
    _note_columns("specialty_concerns", "specialty_id, keyword, weight, created_at, updated_at")
    _note_columns("medicines", "name, generic_name, form, strength, default_dosage, default_frequency, "
                               "default_duration, instructions, is_active, created_at, updated_at")
    _note_columns("holidays", "name, holiday_date, is_full_day, created_at, updated_at")

    # ------------------------------------------------------------------ 1. RBAC
    sql.append("-- roles ---\n")
    for name, description in ROLES.items():
        sql.append(f"INSERT INTO roles (name, description, is_system, created_at, updated_at) "
                   f"VALUES ('{name}', '{_esc(description)}', 1, NOW(), NOW()) "
                   f"ON DUPLICATE KEY UPDATE description = VALUES(description);\n")

    sql.append("\n-- permissions ---\n")
    for code, (module, description) in PERMISSIONS.items():
        sql.append(f"INSERT INTO permissions (code, module, description, created_at, updated_at) "
                   f"VALUES ('{code}', '{module}', '{_esc(description)}', NOW(), NOW()) "
                   f"ON DUPLICATE KEY UPDATE description = VALUES(description);\n")

    sql.append("\n-- role -> permission mapping ---\n")
    for role_name, codes in ROLE_PERMISSIONS.items():
        wanted = list(PERMISSIONS.keys()) if "*" in codes else codes
        for code in wanted:
            sql.append(
                "INSERT INTO role_permissions (role_id, permission_id)\n"
                f"  SELECT r.id, p.id FROM roles r, permissions p WHERE r.name = '{role_name}' "
                f"AND p.code = '{code}'\n"
                "  AND NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id = r.id "
                "AND rp.permission_id = p.id);\n")

    # ------------------------------------------------------------------ 2. MASTERS
    #  Masters come before the doctor block on purpose: the doctor rows are
    #  created with INSERT ... SELECT against specialties, and a SELECT over an
    #  empty table silently inserts 0 rows (no error).
    sql.append("\n-- specialties + symptom/concern mapping ---\n")
    for code, name, description, fee in SPECIALTIES:
        sql.append(f"INSERT INTO specialties (code, name, description, consultation_fee, is_active, "
                   f"created_at, updated_at) VALUES ('{code}', '{_esc(name)}', '{_esc(description)}', {fee}, 1, "
                   f"NOW(), NOW()) ON DUPLICATE KEY UPDATE name = VALUES(name), "
                   f"description = VALUES(description), consultation_fee = VALUES(consultation_fee);\n")
        for keyword in CONCERNS[code]:
            sql.append(
                "INSERT INTO specialty_concerns (specialty_id, keyword, weight, created_at, updated_at)\n"
                f"  SELECT s.id, '{keyword}', 2, NOW(), NOW() FROM specialties s WHERE s.code = '{code}'\n"
                "  AND NOT EXISTS (SELECT 1 FROM specialty_concerns sc WHERE sc.specialty_id = s.id "
                f"AND sc.keyword = '{keyword}');\n")

    sql.append("\n-- medicine master ---\n")
    for name, generic, form, strength, dosage, instructions, duration in MEDICINES:
        sql.append(f"INSERT INTO medicines (name, generic_name, form, strength, default_dosage, "
                   f"default_frequency, default_duration, instructions, is_active, created_at, updated_at) "
                   f"VALUES ('{_esc(name)}', '{_esc(generic)}', '{form}', '{strength}', '{dosage}', '{dosage}', "
                   f"'{duration}', '{_esc(instructions)}', 1, NOW(), NOW())\n"
                   f"  ON DUPLICATE KEY UPDATE generic_name = VALUES(generic_name);\n")

    sql.append("\n-- holidays ---\n")
    for name, md in [("Republic Day", "01-26"), ("Holi", "03-04"), ("Independence Day", "08-15"),
                     ("Diwali", "11-08"), ("New Year", "12-31")]:
        sql.append(f"INSERT INTO holidays (name, holiday_date, is_full_day, created_at, updated_at)\n"
                   f"  SELECT '{name}', CONCAT(YEAR(CURDATE()), '-{md}'), 1, NOW(), NOW()\n"
                   f"  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM holidays h WHERE h.holiday_date = "
                   f"CONCAT(YEAR(CURDATE()), '-{md}'));\n")

    # ------------------------------------------------------------------ 3. STAFF
    sql.append("\n-- demo staff logins (change the passwords in production!) ---\n")
    for full_name, email, role, password, phone in STAFF:
        digest = hash_password(password)
        sql.append(
            "INSERT INTO users (uuid, full_name, email, phone, password_hash, role_id, is_active, "
            "is_verified, must_change_password, phone_verified, failed_login_attempts, "
            "password_changed_at, created_at, updated_at)\n"
            f"  SELECT REPLACE(UUID(),'-',''), '{_esc(full_name)}', '{email}', '{phone}', '{digest}', r.id, "
            f"1, 1, 1, 1, 0, NOW(), NOW(), NOW() FROM roles r WHERE r.name = '{role}'\n"
            "  ON DUPLICATE KEY UPDATE full_name = VALUES(full_name);\n")

    # ------------------------------------------------------------------ 4. DOCTORS
    sql.append("\n-- demo doctor logins (password: Doctor@123) ---\n")
    doctors = [
        ("Dr Arjun Mehra", "dr.arjunmehra@vijayvargiyahospital.in", "GENMED", 500, "MBBS, MD (Internal Medicine)", 14),
        ("Dr Nidhi Sharma", "dr.nidhisharma@vijayvargiyahospital.in", "CARDIOLOGY", 900, "MBBS, MD, DM (Cardiology)", 18),
        ("Dr Rakesh Choudhary", "dr.rakeshchoudhary@vijayvargiyahospital.in", "ORTHO", 700, "MBBS, MS (Orthopaedics)", 12),
        ("Dr Priya Agarwal", "dr.priyaagarwal@vijayvargiyahospital.in", "DERMA", 600, "MBBS, MD (Dermatology)", 9),
        ("Dr Sameer Khan", "dr.sameerkhan@vijayvargiyahospital.in", "PEDIA", 600, "MBBS, MD (Paediatrics)", 15),
        ("Dr Anjali Rathore", "dr.anjalirathore@vijayvargiyahospital.in", "GYNAE", 800, "MBBS, MS (Obs & Gynae)", 16),
        ("Dr Vikas Jain", "dr.vikasjain@vijayvargiyahospital.in", "ENT", 600, "MBBS, MS (ENT)", 11),
        ("Dr Meena Kumari", "dr.meenakumari@vijayvargiyahospital.in", "NEURO", 1000, "MBBS, MD, DM (Neurology)", 13),
    ]
    doctor_digest = hash_password("Doctor@123")
    for idx, (name, email, code, fee, quals, exp) in enumerate(doctors, start=1):
        sql.append(
            "INSERT INTO users (uuid, full_name, email, password_hash, role_id, is_active, is_verified, "
            "must_change_password, phone_verified, failed_login_attempts, password_changed_at, "
            "created_at, updated_at)\n"
            f"  SELECT REPLACE(UUID(),'-',''), '{_esc(name)}', '{email}', '{doctor_digest}', r.id, 1, 1, 1, 1, 0, "
            "NOW(), NOW(), NOW() FROM roles r WHERE r.name = 'DOCTOR'\n"
            "  ON DUPLICATE KEY UPDATE full_name = VALUES(full_name);\n")
        sql.append(
            "INSERT INTO doctors (doctor_code, user_id, specialty_id, full_name, email, qualifications, "
            "experience_years, registration_no, languages, consultation_fee, follow_up_fee, "
            "slot_duration_minutes, daily_capacity, room_number, is_available_for_ai_booking, is_active, "
            "rating_avg, rating_count, created_at, updated_at)\n"
            f"  SELECT 'DOC-{idx:04d}', u.id, s.id, '{_esc(name)}', '{email}', '{_esc(quals)}', {exp}, "
            f"'RMC/RJ/{2010 + idx}/{1000 + idx}', 'Hindi, English', {fee}, {int(fee * 0.6)}, 30, 24, "
            f"'{100 + idx}', 1, 1, 0, 0, NOW(), NOW()\n"
            f"  FROM users u, specialties s WHERE u.email = '{email}' AND s.code = '{code}'\n"
            f"  AND NOT EXISTS (SELECT 1 FROM doctors d WHERE d.email = '{email}');\n")
        for day in range(6):
            sql.append(
                "INSERT INTO doctor_schedules (doctor_id, day_of_week, start_time, end_time, break_start, "
                "break_end, slot_duration_minutes, capacity_per_slot, is_active, created_at, updated_at)\n"
                f"  SELECT d.id, {day}, '09:30:00', '17:30:00', '13:00:00', '14:00:00', 30, 1, 1, NOW(), NOW()\n"
                f"  FROM doctors d WHERE d.email = '{email}'\n"
                "  AND NOT EXISTS (SELECT 1 FROM doctor_schedules ds WHERE ds.doctor_id = d.id "
                f"AND ds.day_of_week = {day});\n")

    # ------------------------------------------------------------------ 5. AUDIT
    problems = audit_columns()
    problems += audit_statement_order("".join(sql))
    if problems:
        sql.append("\n-- WARNING: review the items below before relying on this seed --\n")
        for problem in problems:
            sql.append(f"--   {problem}\n")
    sql.append("\n-- done ---\nSELECT 'Seed applied.' AS status;\n")
    out.write_text("".join(sql))
    return problems


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "sql/03_seed.sql"
    warnings = export(target)
    print(f"Wrote {target} ({len(warnings)} warning(s))")
    for warning in warnings:
        print("  !", warning)
