-- =============================================================================
--  VIJAY VARGIYA GROUP OF HOSPITALS - MySQL schema (generated by app.tools.export_schema)
--  Apply with:
--    mysql -u root -p vijay_vargiya_hospital < sql/02_schema.sql
-- =============================================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS holidays (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(120) NOT NULL, 
	holiday_date DATE NOT NULL, 
	is_full_day BOOL NOT NULL, 
	description VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id),
  UNIQUE KEY `ix_holidays_holiday_date` (`holiday_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS job_runs (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	job_name VARCHAR(60) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	started_at DATETIME NOT NULL, 
	finished_at DATETIME, 
	duration_ms INTEGER, 
	details JSON, 
	error VARCHAR(500), 
	PRIMARY KEY (id),
  KEY `ix_job_runs_started_at` (`started_at`),
  KEY `ix_job_runs_job_name` (`job_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medicines (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(150) NOT NULL, 
	generic_name VARCHAR(150), 
	form VARCHAR(40), 
	strength VARCHAR(60), 
	manufacturer VARCHAR(120), 
	default_dosage VARCHAR(60), 
	default_frequency VARCHAR(60), 
	default_duration VARCHAR(60), 
	instructions VARCHAR(255), 
	is_active BOOL NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id),
  KEY `ix_medicines_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permissions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	code VARCHAR(80) NOT NULL, 
	module VARCHAR(40) NOT NULL, 
	description VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS roles (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(40) NOT NULL, 
	description VARCHAR(255), 
	is_system BOOL NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS specialties (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	code VARCHAR(30) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	description TEXT, 
	consultation_fee NUMERIC(10, 2), 
	is_active BOOL NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code), 
	UNIQUE (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS system_settings (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	`key` VARCHAR(80) NOT NULL, 
	value VARCHAR(500), 
	description VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_permissions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	role_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_id) REFERENCES permissions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS specialty_concerns (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	specialty_id INTEGER NOT NULL, 
	keyword VARCHAR(80) NOT NULL, 
	weight INTEGER NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_specialty_keyword UNIQUE (specialty_id, keyword), 
	FOREIGN KEY(specialty_id) REFERENCES specialties (id) ON DELETE CASCADE,
  KEY `ix_specialty_concerns_specialty_id` (`specialty_id`),
  KEY `ix_specialty_concerns_keyword` (`keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	uuid VARCHAR(36) NOT NULL, 
	full_name VARCHAR(150) NOT NULL, 
	email VARCHAR(150) NOT NULL, 
	phone VARCHAR(20), 
	password_hash VARCHAR(255) NOT NULL, 
	role_id INTEGER NOT NULL, 
	is_active BOOL NOT NULL, 
	is_verified BOOL NOT NULL, 
	must_change_password BOOL NOT NULL, 
	phone_verified BOOL NOT NULL, 
	failed_login_attempts INTEGER NOT NULL, 
	locked_until DATETIME, 
	last_login_at DATETIME, 
	last_login_ip VARCHAR(64), 
	password_changed_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (uuid), 
	UNIQUE (email), 
	FOREIGN KEY(role_id) REFERENCES roles (id),
  KEY `ix_users_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER, 
	user_email VARCHAR(150), 
	user_role VARCHAR(40), 
	action VARCHAR(80) NOT NULL, 
	resource VARCHAR(80) NOT NULL, 
	resource_id VARCHAR(60), 
	previous_value JSON, 
	new_value JSON, 
	ip_address VARCHAR(64), 
	user_agent VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_audit_logs_created_at` (`created_at`),
  KEY `ix_audit_logs_resource` (`resource`),
  KEY `ix_audit_logs_user_id` (`user_id`),
  KEY `ix_audit_logs_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS doctors (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	doctor_code VARCHAR(20) NOT NULL, 
	user_id INTEGER, 
	specialty_id INTEGER NOT NULL, 
	full_name VARCHAR(150) NOT NULL, 
	email VARCHAR(150), 
	phone VARCHAR(20), 
	qualifications VARCHAR(255), 
	experience_years INTEGER, 
	registration_no VARCHAR(60), 
	bio TEXT, 
	languages VARCHAR(150), 
	consultation_fee NUMERIC(10, 2) NOT NULL, 
	follow_up_fee NUMERIC(10, 2), 
	slot_duration_minutes INTEGER NOT NULL, 
	daily_capacity INTEGER NOT NULL, 
	room_number VARCHAR(20), 
	is_available_for_ai_booking BOOL NOT NULL, 
	is_active BOOL NOT NULL, 
	rating_avg NUMERIC(3, 2), 
	rating_count INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(specialty_id) REFERENCES specialties (id),
  KEY `ix_doctors_full_name` (`full_name`),
  UNIQUE KEY `ix_doctors_doctor_code` (`doctor_code`),
  KEY `ix_doctors_specialty_id` (`specialty_id`),
  KEY `ix_doctors_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS login_activity (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER, 
	email_attempted VARCHAR(150) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	reason VARCHAR(200), 
	ip_address VARCHAR(64), 
	user_agent VARCHAR(255), 
	attempt_at DATETIME NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_login_activity_user_id` (`user_id`),
  KEY `ix_login_activity_attempt_at` (`attempt_at`),
  KEY `ix_login_activity_email_attempted` (`email_attempted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER NOT NULL, 
	token_hash VARCHAR(128) NOT NULL, 
	channel VARCHAR(20), 
	expires_at DATETIME NOT NULL, 
	used_at DATETIME, 
	requested_ip VARCHAR(64), 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (token_hash),
  KEY `ix_password_reset_tokens_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS patients (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	patient_code VARCHAR(20) NOT NULL, 
	user_id INTEGER, 
	full_name VARCHAR(150) NOT NULL, 
	date_of_birth DATE, 
	age INTEGER, 
	gender VARCHAR(20), 
	blood_group VARCHAR(8), 
	phone VARCHAR(20) NOT NULL, 
	alternate_phone VARCHAR(20), 
	email VARCHAR(150), 
	address_line VARCHAR(255), 
	city VARCHAR(80), 
	state VARCHAR(80), 
	pincode VARCHAR(12), 
	emergency_contact_name VARCHAR(150), 
	emergency_contact_phone VARCHAR(20), 
	emergency_contact_relation VARCHAR(60), 
	allergies TEXT, 
	chronic_conditions TEXT, 
	notes TEXT, 
	is_active BOOL NOT NULL, 
	created_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_patients_full_name` (`full_name`),
  KEY `ix_patients_phone` (`phone`),
  UNIQUE KEY `ix_patients_patient_code` (`patient_code`),
  KEY `ix_patients_user_id` (`user_id`),
  KEY `ix_patients_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_sessions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	session_key VARCHAR(64) NOT NULL, 
	user_id INTEGER NOT NULL, 
	refresh_token_hash VARCHAR(128) NOT NULL, 
	access_jti VARCHAR(64), 
	ip_address VARCHAR(64), 
	user_agent VARCHAR(255), 
	device VARCHAR(120), 
	is_revoked BOOL NOT NULL, 
	revoked_at DATETIME, 
	revoked_reason VARCHAR(120), 
	expires_at DATETIME NOT NULL, 
	last_seen_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (session_key), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE,
  KEY `ix_user_sessions_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_conversations (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	session_id VARCHAR(64) NOT NULL, 
	patient_id INTEGER, 
	user_id INTEGER, 
	channel VARCHAR(20) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	patient_type VARCHAR(20), 
	stage VARCHAR(30) NOT NULL, 
	pending_json JSON, 
	primary_intent VARCHAR(40), 
	intent_history JSON, 
	concern_summary TEXT, 
	summary TEXT, 
	message_count INTEGER NOT NULL, 
	tool_call_count INTEGER NOT NULL, 
	booking_attempts INTEGER NOT NULL, 
	successful_bookings INTEGER NOT NULL, 
	failed_bookings INTEGER NOT NULL, 
	escalation_count INTEGER NOT NULL, 
	error_count INTEGER NOT NULL, 
	avg_response_ms INTEGER, 
	started_at DATETIME NOT NULL, 
	last_message_at DATETIME, 
	ended_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE SET NULL, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_ai_conversations_started_at` (`started_at`),
  UNIQUE KEY `ix_ai_conversations_session_id` (`session_id`),
  KEY `ix_ai_conversations_status` (`status`),
  KEY `ix_ai_conversations_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS doctor_leaves (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	doctor_id INTEGER NOT NULL, 
	leave_type VARCHAR(20) NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE NOT NULL, 
	start_time TIME, 
	end_time TIME, 
	reason VARCHAR(255), 
	status VARCHAR(20) NOT NULL, 
	approved_by INTEGER, 
	slots_blocked INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id) ON DELETE CASCADE, 
	FOREIGN KEY(approved_by) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_doctor_leaves_start_date` (`start_date`),
  KEY `ix_doctor_leaves_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS doctor_schedules (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	doctor_id INTEGER NOT NULL, 
	day_of_week INTEGER NOT NULL, 
	start_time TIME NOT NULL, 
	end_time TIME NOT NULL, 
	break_start TIME, 
	break_end TIME, 
	slot_duration_minutes INTEGER NOT NULL, 
	capacity_per_slot INTEGER NOT NULL, 
	is_active BOOL NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_doctor_day_start UNIQUE (doctor_id, day_of_week, start_time), 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  KEY `ix_schedule_doctor_day` (`doctor_id`, `day_of_week`),
  KEY `ix_doctor_schedules_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER, 
	patient_id INTEGER, 
	channel VARCHAR(20) NOT NULL, 
	template VARCHAR(60) NOT NULL, 
	subject VARCHAR(180), 
	message TEXT NOT NULL, 
	payload JSON, 
	status VARCHAR(20) NOT NULL, 
	retry_count INTEGER NOT NULL, 
	error VARCHAR(255), 
	provider_reference VARCHAR(120), 
	scheduled_at DATETIME, 
	sent_at DATETIME, 
	read_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  KEY `ix_notifications_status` (`status`),
  KEY `ix_notifications_user_id` (`user_id`),
  KEY `ix_notifications_scheduled_at` (`scheduled_at`),
  KEY `ix_notifications_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS slots (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	doctor_id INTEGER NOT NULL, 
	slot_date DATE NOT NULL, 
	start_time TIME NOT NULL, 
	end_time TIME NOT NULL, 
	capacity INTEGER NOT NULL, 
	booked_count INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	hold_token VARCHAR(64), 
	hold_patient_id INTEGER, 
	hold_expires_at DATETIME, 
	blocked_reason VARCHAR(120), 
	generated_by VARCHAR(20), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_slot_doctor_date_start UNIQUE (doctor_id, slot_date, start_time), 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id) ON DELETE CASCADE, 
	FOREIGN KEY(hold_patient_id) REFERENCES patients (id) ON DELETE SET NULL,
  KEY `ix_slot_lookup` (`doctor_id`, `slot_date`, `status`),
  KEY `ix_slots_hold_token` (`hold_token`),
  KEY `ix_slots_slot_date` (`slot_date`),
  KEY `ix_slots_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_escalations (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	conversation_id INTEGER, 
	patient_id INTEGER, 
	level VARCHAR(20) NOT NULL, 
	reason VARCHAR(255) NOT NULL, 
	detail TEXT, 
	status VARCHAR(20) NOT NULL, 
	assigned_to INTEGER, 
	resolution_notes TEXT, 
	resolved_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE SET NULL, 
	FOREIGN KEY(assigned_to) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_ai_escalations_conversation_id` (`conversation_id`),
  KEY `ix_ai_escalations_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_messages (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	conversation_id INTEGER NOT NULL, 
	`role` VARCHAR(12) NOT NULL, 
	content TEXT NOT NULL, 
	intent VARCHAR(40), 
	confidence NUMERIC(4, 2), 
	tool_calls JSON, 
	structured JSON, 
	latency_ms INTEGER, 
	safety_flag VARCHAR(30), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE,
  KEY `ix_ai_messages_created_at` (`created_at`),
  KEY `ix_ai_messages_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_summaries (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	patient_id INTEGER NOT NULL, 
	conversation_id INTEGER, 
	summary_type VARCHAR(30) NOT NULL, 
	summary TEXT NOT NULL, 
	context_json JSON, 
	generated_by VARCHAR(20), 
	token_estimate INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE SET NULL,
  KEY `ix_ai_summaries_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS appointments (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	appointment_code VARCHAR(24) NOT NULL, 
	patient_id INTEGER NOT NULL, 
	doctor_id INTEGER NOT NULL, 
	specialty_id INTEGER, 
	slot_id INTEGER, 
	appointment_date DATE NOT NULL, 
	start_time TIME NOT NULL, 
	end_time TIME, 
	token_number INTEGER, 
	status VARCHAR(20) NOT NULL, 
	queue_status VARCHAR(20) NOT NULL, 
	source VARCHAR(20) NOT NULL, 
	reason TEXT, 
	ai_concern_summary TEXT, 
	booked_by INTEGER, 
	cancelled_by INTEGER, 
	cancellation_reason VARCHAR(255), 
	rescheduled_from_id INTEGER, 
	checked_in_at DATETIME, 
	checked_out_at DATETIME, 
	reminder_sent_at DATETIME, 
	follow_up_of INTEGER, 
	notes TEXT, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id), 
	FOREIGN KEY(specialty_id) REFERENCES specialties (id), 
	FOREIGN KEY(slot_id) REFERENCES slots (id) ON DELETE SET NULL, 
	FOREIGN KEY(booked_by) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(cancelled_by) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(rescheduled_from_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(follow_up_of) REFERENCES appointments (id) ON DELETE SET NULL,
  KEY `ix_appointments_patient_id` (`patient_id`),
  KEY `ix_appointments_queue_status` (`queue_status`),
  KEY `ix_appointments_status` (`status`),
  UNIQUE KEY `ix_appointments_appointment_code` (`appointment_code`),
  KEY `ix_appointments_appointment_date` (`appointment_date`),
  KEY `ix_appointments_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS slot_hold_history (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	slot_id INTEGER NOT NULL, 
	action VARCHAR(20) NOT NULL, 
	actor VARCHAR(60), 
	conversation_id INTEGER, 
	hold_token VARCHAR(64), 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(slot_id) REFERENCES slots (id) ON DELETE CASCADE, 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE SET NULL,
  KEY `ix_slot_hold_history_slot_id` (`slot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_concerns (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	patient_id INTEGER, 
	conversation_id INTEGER, 
	appointment_id INTEGER, 
	specialty_id INTEGER, 
	concern_text TEXT NOT NULL, 
	keywords JSON, 
	duration_text VARCHAR(80), 
	severity VARCHAR(20), 
	urgency VARCHAR(20) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	history_json JSON, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE SET NULL, 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(specialty_id) REFERENCES specialties (id) ON DELETE SET NULL,
  KEY `ix_ai_concerns_patient_id` (`patient_id`),
  KEY `ix_ai_concerns_urgency` (`urgency`),
  KEY `ix_ai_concerns_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_tool_calls (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	conversation_id INTEGER, 
	message_id INTEGER, 
	tool_name VARCHAR(60) NOT NULL, 
	arguments JSON, 
	result_summary VARCHAR(500), 
	status VARCHAR(20) NOT NULL, 
	error VARCHAR(255), 
	duration_ms INTEGER, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE, 
	FOREIGN KEY(message_id) REFERENCES ai_messages (id) ON DELETE SET NULL,
  KEY `ix_ai_tool_calls_tool_name` (`tool_name`),
  KEY `ix_ai_tool_calls_conversation_id` (`conversation_id`),
  KEY `ix_ai_tool_calls_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consultations (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	consultation_code VARCHAR(24) NOT NULL, 
	appointment_id INTEGER, 
	patient_id INTEGER NOT NULL, 
	doctor_id INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	chief_complaint TEXT, 
	vitals JSON, 
	observations TEXT, 
	diagnosis TEXT, 
	clinical_notes TEXT, 
	advice TEXT, 
	follow_up_required BOOL NOT NULL, 
	follow_up_date DATE, 
	follow_up_notes VARCHAR(255), 
	follow_up_appointment_id INTEGER, 
	started_at DATETIME, 
	completed_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (consultation_code), 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id), 
	FOREIGN KEY(follow_up_appointment_id) REFERENCES appointments (id) ON DELETE SET NULL,
  KEY `ix_consultations_doctor_id` (`doctor_id`),
  KEY `ix_consultations_follow_up_date` (`follow_up_date`),
  KEY `ix_consultations_patient_id` (`patient_id`),
  KEY `ix_consultations_appointment_id` (`appointment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reviews (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	patient_id INTEGER NOT NULL, 
	doctor_id INTEGER, 
	appointment_id INTEGER, 
	review_type VARCHAR(20) NOT NULL, 
	rating INTEGER NOT NULL, 
	title VARCHAR(150), 
	comment TEXT, 
	status VARCHAR(20) NOT NULL, 
	requested_at DATETIME, 
	moderated_by INTEGER, 
	moderated_at DATETIME, 
	admin_note VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id) ON DELETE SET NULL, 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(moderated_by) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_reviews_doctor_id` (`doctor_id`),
  KEY `ix_reviews_status` (`status`),
  KEY `ix_reviews_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_messages (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	notification_id INTEGER, 
	patient_id INTEGER, 
	appointment_id INTEGER, 
	to_number VARCHAR(24) NOT NULL, 
	template VARCHAR(60) NOT NULL, 
	body TEXT NOT NULL, 
	provider VARCHAR(30) NOT NULL, 
	provider_message_id VARCHAR(80), 
	status VARCHAR(20) NOT NULL, 
	error VARCHAR(255), 
	attempts INTEGER NOT NULL, 
	next_retry_at DATETIME, 
	sent_at DATETIME, 
	delivered_at DATETIME, 
	read_at DATETIME, 
	raw_response JSON, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(notification_id) REFERENCES notifications (id) ON DELETE SET NULL, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE SET NULL, 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL,
  KEY `ix_whatsapp_messages_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_routing_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	conversation_id INTEGER, 
	concern_id INTEGER, 
	candidate_specialties JSON, 
	selected_specialty_id INTEGER, 
	candidate_doctors JSON, 
	selected_doctor_id INTEGER, 
	match_score NUMERIC(4, 2), 
	decision VARCHAR(200), 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE, 
	FOREIGN KEY(concern_id) REFERENCES ai_concerns (id) ON DELETE SET NULL, 
	FOREIGN KEY(selected_specialty_id) REFERENCES specialties (id) ON DELETE SET NULL, 
	FOREIGN KEY(selected_doctor_id) REFERENCES doctors (id) ON DELETE SET NULL,
  KEY `ix_ai_routing_log_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	invoice_number VARCHAR(24) NOT NULL, 
	patient_id INTEGER NOT NULL, 
	appointment_id INTEGER, 
	consultation_id INTEGER, 
	doctor_id INTEGER, 
	subtotal NUMERIC(10, 2) NOT NULL, 
	discount_amount NUMERIC(10, 2) NOT NULL, 
	discount_reason VARCHAR(150), 
	tax_percent NUMERIC(5, 2) NOT NULL, 
	tax_amount NUMERIC(10, 2) NOT NULL, 
	total_amount NUMERIC(10, 2) NOT NULL, 
	paid_amount NUMERIC(10, 2) NOT NULL, 
	balance_amount NUMERIC(10, 2) NOT NULL, 
	refunded_amount NUMERIC(10, 2) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	notes TEXT, 
	issued_by INTEGER, 
	issued_at DATETIME NOT NULL, 
	due_date DATE, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(consultation_id) REFERENCES consultations (id) ON DELETE SET NULL, 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id) ON DELETE SET NULL, 
	FOREIGN KEY(issued_by) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_invoices_issued_at` (`issued_at`),
  UNIQUE KEY `ix_invoices_invoice_number` (`invoice_number`),
  KEY `ix_invoices_status` (`status`),
  KEY `ix_invoices_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medical_files (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	patient_id INTEGER NOT NULL, 
	consultation_id INTEGER, 
	appointment_id INTEGER, 
	uploaded_by INTEGER, 
	category VARCHAR(30) NOT NULL, 
	title VARCHAR(180) NOT NULL, 
	original_name VARCHAR(255) NOT NULL, 
	stored_name VARCHAR(255) NOT NULL, 
	file_path VARCHAR(500) NOT NULL, 
	mime_type VARCHAR(120), 
	size_bytes INTEGER, 
	checksum VARCHAR(64), 
	access_level VARCHAR(24) NOT NULL, 
	notes VARCHAR(255), 
	is_archived BOOL NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(consultation_id) REFERENCES consultations (id) ON DELETE SET NULL, 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(uploaded_by) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_medical_files_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medical_records (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	patient_id INTEGER NOT NULL, 
	consultation_id INTEGER, 
	appointment_id INTEGER, 
	doctor_id INTEGER, 
	record_type VARCHAR(30) NOT NULL, 
	title VARCHAR(180) NOT NULL, 
	description TEXT, 
	values_json JSON, 
	severity VARCHAR(20), 
	is_visible_to_patient BOOL NOT NULL, 
	entered_by INTEGER, 
	recorded_at DATETIME NOT NULL, 
	version INTEGER NOT NULL, 
	supersedes_id INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(consultation_id) REFERENCES consultations (id) ON DELETE SET NULL, 
	FOREIGN KEY(appointment_id) REFERENCES appointments (id) ON DELETE SET NULL, 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id) ON DELETE SET NULL, 
	FOREIGN KEY(entered_by) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(supersedes_id) REFERENCES medical_records (id) ON DELETE SET NULL,
  KEY `ix_medical_records_patient_id` (`patient_id`),
  KEY `ix_medical_records_consultation_id` (`consultation_id`),
  KEY `ix_medical_records_recorded_at` (`recorded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescriptions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	prescription_code VARCHAR(24) NOT NULL, 
	consultation_id INTEGER, 
	patient_id INTEGER NOT NULL, 
	doctor_id INTEGER NOT NULL, 
	diagnosis_summary TEXT, 
	notes TEXT, 
	advice TEXT, 
	status VARCHAR(20) NOT NULL, 
	pdf_path VARCHAR(500), 
	issued_at DATETIME NOT NULL, 
	valid_until DATE, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(consultation_id) REFERENCES consultations (id) ON DELETE SET NULL, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id),
  UNIQUE KEY `ix_prescriptions_prescription_code` (`prescription_code`),
  KEY `ix_prescriptions_patient_id` (`patient_id`),
  KEY `ix_prescriptions_doctor_id` (`doctor_id`),
  KEY `ix_prescriptions_consultation_id` (`consultation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_items (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	invoice_id INTEGER NOT NULL, 
	item_type VARCHAR(30) NOT NULL, 
	description VARCHAR(200) NOT NULL, 
	quantity INTEGER NOT NULL, 
	unit_price NUMERIC(10, 2) NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,
  KEY `ix_invoice_items_invoice_id` (`invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	payment_code VARCHAR(24) NOT NULL, 
	invoice_id INTEGER, 
	patient_id INTEGER NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	method VARCHAR(20) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	gateway VARCHAR(40), 
	gateway_reference VARCHAR(120), 
	transaction_reference VARCHAR(120), 
	collected_by INTEGER, 
	paid_at DATETIME, 
	failure_reason VARCHAR(255), 
	notes VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE SET NULL, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(collected_by) REFERENCES users (id) ON DELETE SET NULL,
  UNIQUE KEY `ix_payments_payment_code` (`payment_code`),
  KEY `ix_payments_transaction_reference` (`transaction_reference`),
  KEY `ix_payments_invoice_id` (`invoice_id`),
  KEY `ix_payments_status` (`status`),
  KEY `ix_payments_patient_id` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescription_items (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	prescription_id INTEGER NOT NULL, 
	medicine_id INTEGER, 
	medicine_name VARCHAR(150) NOT NULL, 
	dosage VARCHAR(60), 
	frequency VARCHAR(60), 
	duration VARCHAR(60), 
	instructions VARCHAR(255), 
	quantity INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE, 
	FOREIGN KEY(medicine_id) REFERENCES medicines (id) ON DELETE SET NULL,
  KEY `ix_prescription_items_prescription_id` (`prescription_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refunds (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	refund_code VARCHAR(24) NOT NULL, 
	payment_id INTEGER NOT NULL, 
	invoice_id INTEGER, 
	patient_id INTEGER NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	reason VARCHAR(255), 
	status VARCHAR(20) NOT NULL, 
	processed_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (refund_code), 
	FOREIGN KEY(payment_id) REFERENCES payments (id) ON DELETE CASCADE, 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE SET NULL, 
	FOREIGN KEY(patient_id) REFERENCES patients (id) ON DELETE CASCADE, 
	FOREIGN KEY(processed_by) REFERENCES users (id) ON DELETE SET NULL,
  KEY `ix_refunds_payment_id` (`payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
--  REPORTING VIEWS  (read-only helpers for analytics / BI / reception TV)
--  Granted to vvh_readonly and vvh_app by this script.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_appointments_today AS
SELECT a.id, a.appointment_code, p.patient_code, p.full_name AS patient_name, p.phone,
       d.full_name AS doctor_name, s.name AS specialty, a.appointment_date, a.start_time,
       a.token_number, a.status, a.queue_status, a.source
FROM appointments a
JOIN patients p  ON p.id = a.patient_id
LEFT JOIN doctors d ON d.id = a.doctor_id
LEFT JOIN specialties s ON s.id = a.specialty_id
WHERE a.appointment_date = CURDATE();

CREATE OR REPLACE VIEW v_outstanding_invoices AS
SELECT i.id, i.invoice_number, p.patient_code, p.full_name AS patient_name, p.phone,
       i.total_amount, i.paid_amount, i.balance_amount, i.status, i.issued_at, i.due_date
FROM invoices i JOIN patients p ON p.id = i.patient_id
WHERE i.balance_amount > 0 AND i.status IN ('UNPAID','PARTIAL');

CREATE OR REPLACE VIEW v_doctor_daily_load AS
SELECT d.id AS doctor_id, d.doctor_code, d.full_name AS doctor_name, s.name AS specialty,
       a.appointment_date,
       COUNT(*) AS appointments,
       SUM(a.status = 'COMPLETED') AS completed,
       SUM(a.status = 'CANCELLED') AS cancelled,
       SUM(a.queue_status = 'NO_SHOW') AS no_shows,
       SUM(CASE WHEN a.status IN ('PENDING','CONFIRMED') THEN 1 ELSE 0 END) AS upcoming
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
LEFT JOIN specialties s ON s.id = d.specialty_id
GROUP BY d.id, d.doctor_code, d.full_name, s.name, a.appointment_date;

CREATE OR REPLACE VIEW v_ai_daily_summary AS
SELECT DATE(c.started_at) AS day, c.status, COUNT(*) AS conversations,
       SUM(c.escalation_count) AS escalations,
       ROUND(AVG(c.message_count), 1) AS avg_messages,
       SUM(c.successful_bookings) AS bookings,
       ROUND(AVG(c.avg_response_ms), 0) AS avg_response_ms
FROM ai_conversations c
GROUP BY DATE(c.started_at), c.status;

GRANT SELECT ON `vijay_vargiya_hospital`.v_appointments_today TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_outstanding_invoices TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_doctor_daily_load TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_ai_daily_summary TO 'vvh_readonly'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_appointments_today TO 'vvh_app'@'localhost';
GRANT SELECT ON `vijay_vargiya_hospital`.v_outstanding_invoices TO 'vvh_app'@'localhost';

SET FOREIGN_KEY_CHECKS = 1;
-- End of schema
